TASK: "TRAJECTORY"

CV_NUM_SPLITS: 10
ACCURACY_THRESHOLD: 0.8

NUM_NEURONS: 2000
MEMBRANE_THRESHOLD: 2
REFRACTORY_PERIOD: 2
NUM_OUTPUT_NEURONS: 100
LEAK_COEFFICIENT: 0.002
CURRENT_AMPLITUDE: 2  

PRESYNAPTIC_DEGREE: 0.2
SMALL_WORLD_GRAPH_P: 0.2

TRACE_TAU: 50
NUM_WEIGHT_STEPS: 71

WEIGHT_VARIANCE: 10
RELOAD: true
MEMBRANE_RESET: false

PARAM_NAME: "beta"
PARAMETER_VALUES:
  - 0.2
  - 0.3
  - 0.4
