TASK: "TRAJECTORY"
OUTPUT_FEATURES: "statistics"

CV_NUM_SPLITS: 10
ACCURACY_THRESHOLD: 0.8

NUM_NEURONS: 2000
MEMBRANE_THRESHOLD: 2
REFRACTORY_PERIOD: 2
NUM_OUTPUT_NEURONS: 50
LEAK_COEFFICIENT: 0
CURRENT_AMPLITUDE: 2  

PRESYNAPTIC_DEGREE: 0.2
SMALL_WORLD_GRAPH_P: 0.2

TRACE_TAU: 60
NUM_WEIGHT_STEPS: 51

PARAM_NAME: "beta"
PARAMETER_VALUES:
  - 0.2
  - 0.3
  - 0.4
